<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MentorEval.IntegrationTests\**" />
    <Compile Remove="MentorEval.UnitTests\**" />
    <Content Remove="MentorEval.IntegrationTests\**" />
    <Content Remove="MentorEval.UnitTests\**" />
    <EmbeddedResource Remove="MentorEval.IntegrationTests\**" />
    <EmbeddedResource Remove="MentorEval.UnitTests\**" />
    <None Remove="MentorEval.IntegrationTests\**" />
    <None Remove="MentorEval.UnitTests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="QuestPDF" Version="2025.12.1" />
  </ItemGroup>

</Project>
