sonar.projectKey=MentorEval
sonar.working.directory=C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval
sonar.pullrequest.cache.basepath=C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval

33A1B365-4230-4CD5-A83E-74B527ADB522.sonar.projectKey=MentorEval:33A1B365-4230-4CD5-A83E-74B527ADB522
33A1B365-4230-4CD5-A83E-74B527ADB522.sonar.projectName=MentorEval
33A1B365-4230-4CD5-A83E-74B527ADB522.sonar.projectBaseDir=C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval
33A1B365-4230-4CD5-A83E-74B527ADB522.sonar.sourceEncoding=utf-8
33A1B365-4230-4CD5-A83E-74B527ADB522.sonar.tests=
33A1B365-4230-4CD5-A83E-74B527ADB522.sonar.sources=\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Controllers\\AuthController.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Controllers\\EvaluationsController.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Controllers\\HomeController.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Controllers\\ReportsController.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Controllers\\StudentEvaluationsController.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Models\\Answer.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Models\\AppDbContext.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Models\\Course.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Models\\ErrorViewModel.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Models\\Evaluation.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Models\\Question.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Models\\Report.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Models\\Reports\\EvaluationReportDto.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Models\\Reports\\KeywordCountDto.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Models\\Reports\\QuestionReportDto.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Models\\StudentEvaluationFillViewModel.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Models\\User.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Models\\ViewModels\\CourseOption.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Models\\ViewModels\\EvaluationCreateViewModel.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Program.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\CourseQueryService.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\EvaluationCreationService.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\EvaluationFacade.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\EvaluationQueryService.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\ICourseQueryService.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\IEvaluationCreationService.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\IEvaluationQueryService.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\IQuestionFactory.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\IQuestionHandler.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\QuestionFactory.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\Questions\\DropdownQuestionHandler.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\Questions\\Scale10QuestionHandler.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\Questions\\TextQuestionHandler.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\Questions\\YesNoQuestionHandler.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\Validation\\DropdownValidationStrategy.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\Validation\\IQuestionValidationStrategy.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\Validation\\QuestionValidationResolver.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\Validation\\Scale10ValidationStrategy.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\Validation\\TextValidationStrategy.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Evaluations\\Validation\\YesNoValidationStrategy.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\PdfService.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\ReportAnalyticsService.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Security\\CurrentUser.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Services\\Security\\ICurrentUser.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\Debug\\net8.0\\MentorEval.GlobalUsings.g.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\Debug\\net8.0\\MentorEval.AssemblyInfo.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\Debug\\net8.0\\MentorEval.RazorAssemblyInfo.cs",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\css\\site.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\favicon.ico",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\js\\evaluations-create.js",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\js\\site.js",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.css.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.min.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.min.css.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.rtl.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.rtl.css.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.rtl.min.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-grid.rtl.min.css.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.css.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.min.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.min.css.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.rtl.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.rtl.css.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.rtl.min.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-reboot.rtl.min.css.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.css.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.min.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.min.css.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.rtl.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.rtl.css.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.rtl.min.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap-utilities.rtl.min.css.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.css.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.min.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.min.css.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.rtl.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.rtl.css.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.rtl.min.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\css\\bootstrap.rtl.min.css.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.bundle.js",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.bundle.js.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.bundle.min.js",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.bundle.min.js.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.esm.js",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.esm.js.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.esm.min.js",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.esm.min.js.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.js",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.js.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.min.js",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\dist\\js\\bootstrap.min.js.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\bootstrap\\LICENSE",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\jquery-validation-unobtrusive\\jquery.validate.unobtrusive.js",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\jquery-validation-unobtrusive\\jquery.validate.unobtrusive.min.js",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\jquery-validation-unobtrusive\\LICENSE.txt",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\jquery-validation\\dist\\additional-methods.js",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\jquery-validation\\dist\\additional-methods.min.js",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\jquery-validation\\dist\\jquery.validate.js",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\jquery-validation\\dist\\jquery.validate.min.js",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\jquery-validation\\LICENSE.md",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\jquery\\dist\\jquery.js",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\jquery\\dist\\jquery.min.js",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\jquery\\dist\\jquery.min.map",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\wwwroot\\lib\\jquery\\LICENSE.txt",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\appsettings.Development.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\appsettings.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Views\\Auth\\Login.cshtml",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Views\\Auth\\Register.cshtml",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Views\\Evaluations\\Create.cshtml",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Views\\Evaluations\\Index.cshtml",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Views\\Home\\Dashboard.cshtml",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Views\\Home\\Index.cshtml",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Views\\Home\\Privacy.cshtml",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Views\\Shared\\Error.cshtml",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Views\\Shared\\_Layout.cshtml",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Views\\Shared\\_ValidationScriptsPartial.cshtml",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Views\\StudentEvaluations\\Fill.cshtml",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Views\\StudentEvaluations\\Index.cshtml",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Views\\StudentEvaluations\\ThankYou.cshtml",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Views\\_ViewImports.cshtml",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Views\\_ViewStart.cshtml",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Views\\Shared\\_Layout.cshtml.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\Properties\\launchSettings.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\MentorEval.csproj.nuget.dgspec.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\project.assets.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\.vs\\MentorEval\\v17\\DocumentLayout.backup.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\.vs\\MentorEval\\v17\\DocumentLayout.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\bin\\Debug\\net8.0\\MentorEval.deps.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\bin\\Debug\\net8.0\\MentorEval.runtimeconfig.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\bin\\Debug\\net8.0\\MentorEval.staticwebassets.endpoints.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\bin\\Debug\\net8.0\\MentorEval.staticwebassets.runtime.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\Debug\\net8.0\\ApiEndpoints.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\Debug\\net8.0\\MentorEval.sourcelink.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\Debug\\net8.0\\rjimswa.dswa.cache.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\Debug\\net8.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\Debug\\net8.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\Debug\\net8.0\\rpswa.dswa.cache.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\Debug\\net8.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\Debug\\net8.0\\staticwebassets.build.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\Debug\\net8.0\\staticwebassets.development.json",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\Debug\\net8.0\\scopedcss\\bundle\\MentorEval.styles.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\Debug\\net8.0\\scopedcss\\projectbundle\\MentorEval.bundle.scp.css",\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\obj\\Debug\\net8.0\\scopedcss\\Views\\Shared\\_Layout.cshtml.rz.scp.css"

33A1B365-4230-4CD5-A83E-74B527ADB522.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\.sonarqube\\out\\0"
33A1B365-4230-4CD5-A83E-74B527ADB522.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\.sonarqube\\out\\0\\Issues.json"
33A1B365-4230-4CD5-A83E-74B527ADB522.sonar.cs.scanner.telemetry=\
"C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\.sonarqube\\out\\0\\Telemetry.json"

33A1B365-4230-4CD5-A83E-74B527ADB522.sonar.working.directory=C:\\Users\\Krajancic Ivan\\Downloads\\MentorEval_merged\\MentorEval\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9002
sonar.visualstudio.enable=false

sonar.modules=33A1B365-4230-4CD5-A83E-74B527ADB522

